"""
Routing helpers.
"""
from functools import partial
from starlette.convertors import CONVERTER_TYPES, Convertor
from starlette.routing import Route


Get  = partial(Route, methods = ["GET"])
Post = partial(Route, methods = ["POST"])


class ContainerIdConvertor(Convertor):
    """
    Restrict URL path parameters which are container ids.

    Allows strings of only 12–64 hexadecimal digits during both URL matching
    and URL generation.

    This serves as a filter for what gets through to actually hitting the
    Docker API, and is a precaution against enumeration attacks of the default
    two-word container names automatically generated by Docker.
    """
    # Truncated container ids are 12 hexadecimal digits, full ids 64
    regex = "[0-9a-f]{12,64}"

    def convert(self, value):
        return str(value)

    def to_string(self, value):
        value = str(value)
        assert set("012345679abcdef") == set(value), "May only contain hexadecimal digits"
        assert 12 <= len(value) <= 64, "May not be shorter than 12 digits or more than 64"
        return value


CONVERTOR_TYPES["container"] = ContainerIdConvertor()
